[functions.generate-report]
verify_jwt = false

[functions.generate-pdf]
verify_jwt = false

[functions.send-pdf-webhook]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.stripe-checkout]
verify_jwt = true

[functions.regenerate-report]
verify_jwt = false

[functions.resend-report]
verify_jwt = false

[functions.generate-mini-reading]
verify_jwt = false
